CREATE USER 'tyler'@'localhost' IDENTIFIED BY 'password';

GRANT ALL PRIVILEGES ON *.* TO 'tyler'@'localhost' WITH GRANT OPTION;

CREATE USER 'tyler'@'%' IDENTIFIED BY 'password';

GRANT ALL PRIVILEGES ON *.* TO 'tyler'@'%' WITH GRANT OPTION;

FLUSH PRIVILEGES;